CREATE TABLE users (
    id VARCHAR PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL
);

CREATE TABLE lists (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title VARCHAR(30) NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'TODO' CHECK (status IN ('TODO', 'IN PROGRESS', 'DONE')) NOT NULL,
    is_public BOOLEAN NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE items (
    id SERIAL PRIMARY KEY,
    list_id INTEGER NOT NULL REFERENCES lists (id) ON DELETE CASCADE,
    created_by VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    item_order INTEGER NOT NULL,
    is_done BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE item_suggestions (
    item_id INTEGER NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    list_id INTEGER NOT NULL REFERENCES lists (id) ON DELETE CASCADE,
    suggested_by VARCHAR NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    accepted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (item_id, list_id)
);

CREATE TABLE tag (
    id SERIAL PRIMARY KEY,
    created_by VARCHAR NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title VARCHAR(30) NOT NULL
);

CREATE TABLE list_tag (
    list_id INTEGER NOT NULL REFERENCES lists (id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES tag (id) ON DELETE CASCADE,
    PRIMARY KEY (list_id, tag_id)
);